# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoaPodsHomework' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoaPodsHomework
	pod 'Nuke', '~> 4.1'
	pod 'DynamicButton', '~> 3.1.0'
	pod 'DynamicColor', '~> 3.2'
	pod 'DynamicFont', '~> 1.0'

end
